aws.credential.user.home: "/Users/mjones/"
aws.credential.profile: "default"

# Kinesis Properties
aws.kinesis.region: us-east-1
aws.kinesis.clientTimeout: 600000
#aws.kinesis.appName: dx_cpp_rb_dev
#aws.kinesis.inputStream: rasura-request
#aws.kinesis.outputStream: rasura-response
aws.kinesis.streamPosition: TRIM_HORIZON
aws.kinesis.backOffInMillis: 3000
aws.kinesis.checkPointInMillis: 60000
aws.kinesis.retries: 10
#aws.kinesis.useProxy: true

